using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// Top-level controller for the Main Menu scene.
/// Manages toggling between the main menu view (round buttons) 
/// and the character setting panel.
/// </summary>
public class MainMenuManager : MonoBehaviour
{
    [Header("Panels")]
    public GameObject mainMenuPanel;
    public GameObject characterSettingPanel;

    [Header("Round Scene Mapping")]
    [Tooltip("Scene names for each round. Index 0 = Round 1, etc.")]
    public string[] roundSceneNames = new string[]
    {
        "Peashooter_Test",
        "Map1",
        "SampleMap"
    };

    [Header("Data")]
    public CharacterData[] availableCharacters;
    public EquipmentData[] allEquipment;

    [Header("Preview")]
    public Transform characterPreviewSpot;
    public Camera previewCamera;

    private CharacterSettingUI characterSettingUI;

    void Start()
    {
        // Ensure GameDataCarrier exists
        if (GameDataCarrier.Instance == null)
        {
            GameObject carrier = new GameObject("GameDataCarrier");
            carrier.AddComponent<GameDataCarrier>();
        }

        characterSettingUI = characterSettingPanel.GetComponent<CharacterSettingUI>();

        // Wire up buttons dynamically at runtime to ensure they work
        WireUpButtons();

        ShowMainMenu();
    }

    private void WireUpButtons()
    {
        if (mainMenuPanel != null)
        {
            UnityEngine.UI.Button[] buttons = mainMenuPanel.GetComponentsInChildren<UnityEngine.UI.Button>(true);
            foreach (var btn in buttons)
            {
                btn.onClick.RemoveAllListeners();
                string btnName = btn.gameObject.name;
                if (btnName.Contains("Round 1")) btn.onClick.AddListener(OnRound1Clicked);
                else if (btnName.Contains("Round 2")) btn.onClick.AddListener(OnRound2Clicked);
                else if (btnName.Contains("Round 3")) btn.onClick.AddListener(OnRound3Clicked);
                else if (btnName.Contains("Character Setting")) btn.onClick.AddListener(OnCharacterSettingClicked);
            }
        }
    }

    /// <summary>
    /// Show the main menu with round buttons.
    /// </summary>
    public void ShowMainMenu()
    {
        mainMenuPanel.SetActive(true);
        characterSettingPanel.SetActive(false);
    }

    /// <summary>
    /// Show the character setting panel.
    /// </summary>
    public void ShowCharacterSetting()
    {
        mainMenuPanel.SetActive(false);
        characterSettingPanel.SetActive(true);

        if (characterSettingUI != null)
        {
            characterSettingUI.Initialize(availableCharacters, allEquipment, characterPreviewSpot);
            
            // Wire up the new back button generated by CharacterSettingUI
            if (characterSettingUI.backButton != null)
            {
                characterSettingUI.backButton.onClick.RemoveAllListeners();
                characterSettingUI.backButton.onClick.AddListener(OnBackClicked);
            }
        }
    }

    /// <summary>
    /// Called when a round button is clicked.
    /// </summary>
    public void OnRoundSelected(int roundNumber)
    {
        // Ensure a character is selected, default to first if not
        if (GameDataCarrier.Instance != null && !GameDataCarrier.Instance.HasSelection)
        {
            if (availableCharacters != null && availableCharacters.Length > 0)
            {
                GameDataCarrier.Instance.SelectCharacter(availableCharacters[0]);
            }
        }

        int index = roundNumber - 1;
        if (index >= 0 && index < roundSceneNames.Length)
        {
            SceneManager.LoadScene(roundSceneNames[index]);
        }
        else
        {
            Debug.LogWarning($"[MainMenuManager] Invalid round number: {roundNumber}");
        }
    }

    // Button callbacks for each round (for UnityEvent binding)
    public void OnRound1Clicked()
    {
        Debug.Log(">>> CLICKED: Round 1!");
        OnRoundSelected(1);
    }
    
    public void OnRound2Clicked()
    {
        Debug.Log(">>> CLICKED: Round 2!");
        OnRoundSelected(2);
    }
    
    public void OnRound3Clicked()
    {
        Debug.Log(">>> CLICKED: Round 3!");
        OnRoundSelected(3);
    }
    
    public void OnCharacterSettingClicked()
    {
        Debug.Log(">>> CLICKED: Character Setting!");
        ShowCharacterSetting();
    }
    
    public void OnBackClicked()
    {
        Debug.Log(">>> CLICKED: Back to Main Menu!");
        ShowMainMenu();
    }
}
